name: CI

env:
  node-version: 18.x

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup.node
    - name: Lint
      run: pnpm lint
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup.node
    - name: Generate docs
      run: pnpm doc
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup.node
    - name: Env info
      run: |
        echo "Node $(node -v)"
        echo "pnpm v$(pnpm -v)"
    - name: Test
      run: pnpm test
  e2e:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup.node
    - name: End to end tests
      run: pnpm test:e2e
